#########################################
# Create an `apis_ontology.Institution` #
# from a wikidata RDF endpoint          #
#########################################
superclass = "apis_ontology.models.Institution"
regex = "http://www.wikidata.org.*"
[[attributes]]
# name
sparql = """
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX schema: <http://schema.org/>
SELECT ?name
WHERE {
  ?something schema:about ?institution .
  OPTIONAL{
  	?institution rdfs:label ?label_de .
	FILTER(lang(?label_de) = "de")
  }
  OPTIONAL{
  	?institution rdfs:label ?label_en .
	FILTER(lang(?label_en) = "en")
  }
  ?institution rdfs:label ?label .
  BIND(COALESCE(?label_de, ?label_en, ?label) AS ?name)
}
"""
[[attributes]]
# sameAs
sparql = '''
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT (GROUP_CONCAT(?sameas_pre; separator='|') as ?sameas)
WHERE {
  ?subject wdtn:P227|wdtn:P1566|wdtn:P214|wdtn:P244 ?sameas_pre
}
GROUP BY ?subject
'''
