#########################################
# Create an `apis_ontology.Institution` #
# from a wikidata RDF endpoint          #
#########################################

[[filters]]
"wikibase:directClaim" = "wdt:P910" 

[attributes]
name = '''
SELECT (COALESCE(?label_de, ?label_en, ?label) AS ?name)
WHERE {
?subject a wikibase:Item .
  OPTIONAL{
  	?subject rdfs:label ?label_de .
	FILTER(lang(?label_de) = "de")
  }
  OPTIONAL{
  	?subject rdfs:label ?label_en .
	FILTER(lang(?label_en) = "en")
  }
  OPTIONAL {
  ?subject rdfs:label ?label .}
  }
'''
start = "wdt:P571"
end = "wdt:P576"
same_as = "wdtn:P227|wdtn:P1566|wdtn:P214|wdtn:P244"

#[relations] TODO: add again once https://github.com/acdh-oeaw/apis-core-rdf/issues/1716 is resolved
#"apis_ontology.gelegenin" = { curies = "wdt:P159", obj = "apis_ontology.place"}
