#####################################################
# Create an E74_Group from a d-nb.info RDF endpoint #
#####################################################

[[filters]]
"rdf:type" = "gndo:CorporateBody"
[[filters]]
"rdf:type" = "gndo:OrganOfCorporateBody"

[attributes]
label = "gndo:preferredNameForTheCorporateBody"
start = "gndo:dateOfEstablishment" 
end = "gndo:dateOfTermination"
same_as = "owl:sameAs"

[relations]
"apis_ontology.gelegenin" = { curies = "gndo:placeOfBusiness", obj = "apis_ontology.place"}
