##############################################
# Create an entity `apis_ontology.Person`
# from a wikidata RDF endpoint
##############################################
[[filters]]
"wdt:P31" = "wd:Q5"

[attributes]
forename = "wdt:P735/rdfs:label"
surname = "wdt:P734/rdfs:label"
start = "wdt:P569"
end = "wdt:P570"
same_as = "wdtn:P227|wdtn:P1566|wdtn:P214|wdtn:P244" 
profession_profession_m2m = "wdt:P106"

[relations]
"apis_ontology.starbin" = { curies = "wdt:P20", obj = "apis_ontology.place"}
"apis_ontology.wurdegeborenin" = { curies = "wdt:P19", obj = "apis_ontology.place" }

