######################################################
# Create an E21_Person from a d-nb.info RDF endpoint #
######################################################
superclass = "apis_ontology.models.Person"
regex = "https://d-nb.info.*"
[[attributes]]
# name
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?surname
WHERE {
  ?subject gndo:preferredNameEntityForThePerson/gndo:surname ?name .
  BIND(?name AS ?surname)
}
"""
[[attributes]]
# first_name
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?forename
WHERE {
  ?subject gndo:preferredNameEntityForThePerson/gndo:forename ?first_name .
  BIND(?first_name as ?forename)
}
"""
[[attributes]]
# profession
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT (GROUP_CONCAT(?professionlist) AS ?profession)
WHERE {
  ?subject gndo:professionOrOccupation ?profession_seq.
  ?profession_seq ?seq ?professionlist
}
GROUP BY ?subject
"""
[[attributes]]
# date_of_birth
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?start_date_written
WHERE {
  ?subject gndo:dateOfBirth ?start_date_written .
}
"""
[[attributes]]
# date_of_death
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?end_date_written
WHERE {
  ?subject gndo:dateOfDeath ?end_date_written .
}
"""
[[attributes]]
# place_of_birth
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?place_of_birth
WHERE {
  ?subject gndo:placeOfBirth ?place_of_birth
}
"""
