######################################################
# Create an E21_Person from a d-nb.info RDF endpoint #
######################################################
[[filters]]
"rdf:type" = "gndo:DifferentiatedPerson"

[attributes]
forename = ["gndo:forename", "gndo:preferredNameEntityForThePerson/gndo:forename"]
surname = ["gndo:surname", "gndo:preferredNameEntityForThePerson/gndo:surname"]
alternative_names = "gndo:variantNameForThePerson"
start = "gndo:dateOfBirth"
end = "gndo:dateOfDeath"
same_as = "owl:sameAs"
profession_profession_m2m = "gndo:professionOrOccupation"

[relations]
"apis_ontology.starbin" = { curies = "gndo:placeOfDeath", obj = "apis_ontology.place" }
"apis_ontology.wurdegeborenin" = { curies = "gndo:placeOfBirth", obj = "apis_ontology.place" }

