
####################################################
# Create an E53_Place from a wikidata RDF endpoint #
####################################################
[[filters]]
"wikibase:directClaim" = "wdt:P625" 

[attributes]
label = '''
SELECT (COALESCE(?label_de, ?label_en, ?official_label, ?label) AS ?label)
WHERE {
  ?subject a wikibase:Item .
  OPTIONAL { ?subject wdt:P1448/rdfs:label ?official_label }
  OPTIONAL{
  	?subject rdfs:label ?label_de .
	FILTER(lang(?label_de) = "de")
  }
  OPTIONAL{
  	?subject rdfs:label ?label_en .
	FILTER(lang(?label_en) = "en")
  }
  OPTIONAL{
  	?subject rdfs:label ?label .
  }
}
'''
longitude = '''
SELECT ?longitude
WHERE {
  ?subject wdt:P625 ?geo1 .
  BIND(REPLACE(str(?geo1), "Point\\((\\d+\\.\\d+).*$", "$1") as ?longitude)
  }
''' 
latitude = '''
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?latitude
WHERE {
  ?subject wdt:P625 ?geo1 .
  BIND(REPLACE(str(?geo1), "Point\\((\\d+\\.\\d+) (\\d+\\.\\d+).*$", "$2") as ?latitude)
  }
'''
same_as = "wdtn:P227|wdtn:P1566|wdtn:P214|wdtn:P244"

