
####################################################
# Create an E53_Place from a wikidata RDF endpoint #
####################################################
superclass = "apis_ontology.models.Place"
regex = "http://www.wikidata.org.*"
[[attributes]]
# label
sparql = """
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX schema: <http://schema.org/>
SELECT ?label
WHERE {
  ?something schema:about ?subject .
  ?subject rdfs:label ?label .
  OPTIONAL { ?subject wdt:P1448/rdfs:label ?official_label }
  OPTIONAL{
  	?subject rdfs:label ?label_de .
	FILTER(lang(?label_de) = "de")
  }
  OPTIONAL{
  	?subject rdfs:label ?label_en .
	FILTER(lang(?label_en) = "en")
  }
  BIND(COALESCE(?label_de, ?label_en, ?official_label, ?label) AS ?label)
}
"""
[[attributes]]
# longitude
sparql = '''
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?longitude
WHERE {
  ?subject wdt:P625 ?geo1 .
  BIND(REPLACE(str(?geo1), "Point\\((\\d+\\.\\d+).*$", "$1") as ?longitude)
  }
'''
[[attributes]]
# latitude
sparql = '''
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?latitude
WHERE {
  ?subject wdt:P625 ?geo1 .
  BIND(REPLACE(str(?geo1), "Point\\((\\d+\\.\\d+) (\\d+\\.\\d+).*$", "$2") as ?latitude)
  }
'''
[[attributes]]
# sameAs
sparql = '''
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT (GROUP_CONCAT(?sameas_pre; separator='|') as ?sameas)
WHERE {
  ?subject wdtn:P227|wdtn:P1566|wdtn:P214|wdtn:P244 ?sameas_pre
}
GROUP BY ?subject
'''
