#####################################################
# Create an E53_Place from a d-nb.info RDF endpoint #
# the second regex is for testing

[[filters]]
"rdf:type" = "gndo:TerritorialCorporateBodyOrAdministrativeUnit"

[attributes]
label = "gndo:preferredNameForThePlaceOrGeographicName"
same_as = "owl:sameAs"
longitude = '''
SELECT ?longitude
WHERE {
  ?subject geo:hasGeometry ?geo1 .
  ?geo1 geo:asWKT ?point .
  BIND(REPLACE(str(?point), "Point \\( \\+?(-?\\d+.\\d+).*", "$1") as ?longitude)
  }
'''
latitude = '''
SELECT ?latitude
WHERE {
  ?subject geo:hasGeometry ?geo1 .
  ?geo1 geo:asWKT ?point .
  BIND(REPLACE(str(?point), "^Point\\s*\\(\\s*[+-]?\\d+\\.\\d+\\s+([+-]?\\d+\\.\\d+)\\s*\\)$", "$1") as ?latitude)
  }
'''
