##############################################
# Create an entity `apis_ontology.Place`
# from a wikidata RDF endpoint
##############################################
model = "apis_ontology.Place"
# We filter for rdf documents that contain a wdt:P1566,
# which is the GeoNames ID
filter_sparql = """
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
ASK {
  ?item wdt:P1566 ?obj .
}
"""
[[attributes]]
# name
sparql = """
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX schema: <http://schema.org/>
SELECT ?name
WHERE {
  ?something schema:about ?subject .
  ?subject rdfs:label ?label .
  OPTIONAL { ?subject wdt:P1448/rdfs:label ?official_label }
  BIND(COALESCE(?official_label, ?label) AS ?name)
}
"""
[[attributes]]
# lng
sparql = '''
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?lng
WHERE {
  ?subject wdt:P625 ?geo1 .
  BIND(REPLACE(str(?geo1), "Point\\((\\d+\\.\\d+).*$", "$1") as ?lng)
  }
'''
[[attributes]]
# lat
sparql = '''
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?lat
WHERE {
  ?subject wdt:P625 ?geo1 .
  BIND(REPLACE(str(?geo1), "Point\\((\\d+\\.\\d+) (\\d+\\.\\d+).*$", "$2") as ?lat)
  }
'''
