#####################################################
# Create an E53_Place from a d-nb.info RDF endpoint #
#####################################################
superclass = "apis_ontology.models.Place"
regex = "https://d-nb.info.*"
[[attributes]]
# name
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?label
WHERE {
  ?subject gndo:preferredNameForThePlaceOrGeographicName ?label
}
"""
[[attributes]]
# longitude
sparql = '''
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
SELECT ?longitude
WHERE {
  ?subject geo:hasGeometry ?geo1 .
  ?geo1 geo:asWKT ?point .
  BIND(REPLACE(str(?point), "Point \\( \\+(\\d+.\\d+).*", "$1") as ?longitude)
  }
'''
[[attributes]]
# latitude
sparql = '''
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
SELECT ?latitude
WHERE {
  ?subject geo:hasGeometry ?geo1 .
  ?geo1 geo:asWKT ?point .
  BIND(REPLACE(str(?point), "Point \\( \\+(\\d+.\\d+) \\+(\\d+.\\d+) .$", "$2") as ?latitude)
  }
'''
