# Generated by Django 4.2.10 on 2024-04-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oebl', '0021_dedomination'),
        ('oebl', '0021_parentprofession'),
    ]

    operations = [
    ]
