# Generated by Django 4.1.11 on 2023-09-22 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis_metainfo', '0006_delete_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('rootobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.rootobject')),
                ('start_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_start_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_end_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_start_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_end_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_date_written', models.CharField(blank=True, max_length=255, null=True, verbose_name='Start')),
                ('end_date_written', models.CharField(blank=True, max_length=255, null=True, verbose_name='End')),
                ('review', models.BooleanField(default=False, help_text='Should be set to True, if the data record holds up quality standards.')),
                ('status', models.CharField(max_length=100)),
                ('references', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('kind', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_metainfo.rootobject', models.Model),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('rootobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.rootobject')),
                ('start_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_start_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_end_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_start_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_end_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_date_written', models.CharField(blank=True, max_length=255, null=True, verbose_name='Start')),
                ('end_date_written', models.CharField(blank=True, max_length=255, null=True, verbose_name='End')),
                ('review', models.BooleanField(default=False, help_text='Should be set to True, if the data record holds up quality standards.')),
                ('status', models.CharField(max_length=100)),
                ('references', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('kind', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_metainfo.rootobject', models.Model),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('rootobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.rootobject')),
                ('start_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_start_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_end_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_start_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_end_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_date_written', models.CharField(blank=True, max_length=255, null=True, verbose_name='Start')),
                ('end_date_written', models.CharField(blank=True, max_length=255, null=True, verbose_name='End')),
                ('review', models.BooleanField(default=False, help_text='Should be set to True, if the data record holds up quality standards.')),
                ('status', models.CharField(max_length=100)),
                ('references', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('kind', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='longitude')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_metainfo.rootobject', models.Model),
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('rootobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.rootobject')),
                ('start_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_start_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_end_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_start_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_end_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_date_written', models.CharField(blank=True, max_length=255, null=True, verbose_name='Start')),
                ('end_date_written', models.CharField(blank=True, max_length=255, null=True, verbose_name='End')),
                ('review', models.BooleanField(default=False, help_text='Should be set to True, if the data record holds up quality standards.')),
                ('status', models.CharField(max_length=100)),
                ('references', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('kind', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_metainfo.rootobject', models.Model),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('rootobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.rootobject')),
                ('start_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_start_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_end_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_start_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_end_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_date_written', models.CharField(blank=True, max_length=255, null=True, verbose_name='Start')),
                ('end_date_written', models.CharField(blank=True, max_length=255, null=True, verbose_name='End')),
                ('review', models.BooleanField(default=False, help_text='Should be set to True, if the data record holds up quality standards.')),
                ('status', models.CharField(max_length=100)),
                ('references', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, help_text='The persons´s forename. In case of more then one name...', max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male'), ('third gender', 'third gender')], max_length=15, null=True)),
                ('title', models.ManyToManyField(blank=True, to='apis_ontology.title')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_metainfo.rootobject', models.Model),
        ),
    ]
