# Generated by Django 4.1.11 on 2023-09-27 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0003_alter_event_kind_alter_institution_kind_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profession',
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis_ontology.profession')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.ManyToManyField(blank=True, to='apis_ontology.profession'),
        ),
    ]
