# Generated by Django 4.1.11 on 2023-10-03 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('apis_ontology', '0006_source_content_type_source_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='content_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='source',
            name='object_id',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
