# Generated by Django 4.2.8 on 2023-12-14 08:30

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0010_alter_text_kind"),
    ]

    operations = [UnaccentExtension()]
