# Generated by Django 4.2.8 on 2023-12-14 08:30

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0010_alter_text_kind'),
    ]

    operations = [
        UnaccentExtension()
    ]
