# Generated by Django 4.2.10 on 2024-03-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0015_event_name_institution_name_person_name_place_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='surname',
        ),
    ]
