# Generated by Django 4.2.10 on 2024-04-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0019_person_external_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='kind',
            field=models.CharField(blank=True, choices=[(2, 'ÖBL Haupttext'), (3, 'ÖBL Kurzinfo'), (6, 'Online Edition Haupttext'), (7, 'Nachrecherche'), (8, 'Soziale Herkunft'), (9, 'Verwandtschaft'), (10, 'Ausbildung / Studium / Studienreisen und diesbezügliche Ortsangaben'), (11, 'Berufstätigkeit / Lebensstationen und geographische Lebensmittelpunkte'), (12, 'Mitgliedschaften, Orden, Auszeichnungen und diesbezügliche Ortsangaben'), (13, 'Literatur'), (14, 'Beruf(e)'), (15, 'Sterbedatum'), (16, 'Adelsprädikat'), (17, 'Übersiedlung, Emigration, Remigration'), (18, 'Weitere Namensformen'), (19, 'Geburtsdatum'), (20, 'Sterbeort'), (21, 'Geburtsort'), (22, 'Religion(en)'), (23, 'Name'), (24, 'Übersiedlungen, Emigration, Remigration'), (25, 'Pseudonyme'), (26, 'Soziale Herkunft'), (27, 'ÖBL Werkverzeichnis')], max_length=255, null=True),
        ),
    ]
