# Generated by Django 4.2.10 on 2024-04-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0012_remove_rootobject_deprecated_name'),
        ('apis_ontology', '0020_alter_text_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dedomination',
            fields=[
                ('rootobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.rootobject')),
                ('name', models.CharField()),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_metainfo.rootobject',),
        ),
    ]
