# Generated by Django 4.2.10 on 2024-04-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0023_alter_dedomination_options_person_profession_father_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='label',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
