# Generated by Django 4.2.10 on 2024-04-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0012_remove_rootobject_deprecated_name'),
        ('apis_ontology', '0024_alter_place_label_alter_place_latitude_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dedomination',
            new_name='Denomination',
        ),
    ]
