# Generated by Django 4.2.10 on 2024-04-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0025_rename_dedomination_denomination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='published',
        ),
        migrations.RemoveField(
            model_name='event',
            name='review',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='published',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='review',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='status',
        ),
        migrations.RemoveField(
            model_name='person',
            name='published',
        ),
        migrations.RemoveField(
            model_name='person',
            name='review',
        ),
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
        migrations.RemoveField(
            model_name='place',
            name='published',
        ),
        migrations.RemoveField(
            model_name='place',
            name='review',
        ),
        migrations.RemoveField(
            model_name='place',
            name='status',
        ),
        migrations.RemoveField(
            model_name='work',
            name='published',
        ),
        migrations.RemoveField(
            model_name='work',
            name='review',
        ),
        migrations.RemoveField(
            model_name='work',
            name='status',
        ),
    ]
