# Generated by Django 4.2.10 on 2024-04-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0027_person_adelspraedikat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
