# Generated by Django 4.2.10 on 2024-04-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0028_delete_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='references',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='references',
        ),
        migrations.RemoveField(
            model_name='place',
            name='references',
        ),
        migrations.RemoveField(
            model_name='work',
            name='references',
        ),
    ]
