# Generated by Django 4.2.10 on 2024-04-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0029_remove_event_references_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="first_name",
            new_name="forename",
        ),
    ]
