# Generated by Django 4.2.10 on 2024-04-15 08:59

import apis_core.generic.abc
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis_ontology', '0030_rename_first_name_person_forename'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionPerson',
            fields=[
                ('rootobject_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='apis_metainfo.rootobject')),
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_start_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_end_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_start_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_end_date', models.DateField(blank=True, editable=False, null=True)),
                ('start_date_written', models.CharField(blank=True, max_length=255, null=True, verbose_name='Start')),
                ('end_date_written', models.CharField(blank=True, max_length=255, null=True, verbose_name='End')),
                ('notes', models.TextField(blank=True, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('forename', models.CharField(blank=True, help_text='The persons´s forename. In case of more then one name...', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male'), ('third gender', 'third gender')], max_length=15, null=True)),
                ('external_resources', models.CharField(blank=True, null=True, verbose_name='Externe Verweise')),
                ('references', models.TextField(blank=True, null=True)),
                ('oebl_haupttext', models.TextField(blank=True, verbose_name='ÖBL Haupttext')),
                ('oebl_kurzinfo', models.TextField(blank=True, verbose_name='ÖBL Kurzinfo')),
                ('online_edition_haupttext', models.TextField(blank=True, verbose_name='Online Edition Haupttext')),
                ('nachrecherche', models.TextField(blank=True)),
                ('soziale_herkunft', models.TextField(blank=True)),
                ('verwandtschaft', models.TextField(blank=True)),
                ('ausbildung_studium_studienreise', models.TextField(blank=True, verbose_name='Ausbildung / Studium / Studienreisen und diesbezügliche Ortsangaben')),
                ('berufstaetigkeit_lebenstationen', models.TextField(blank=True, verbose_name='Berufstätigkeit / Lebensstationen und geographische Lebensmittelpunkte')),
                ('mitgliedschaften_orden_auszeichnungen', models.TextField(blank=True, verbose_name='Mitgliedschaften, Orden, Auszeichnungen und diesbezügliche Ortsangaben')),
                ('literatur', models.TextField(blank=True)),
                ('berufe', models.TextField(blank=True)),
                ('sterbedatum', models.TextField(blank=True)),
                ('adelspraedikat', models.TextField(blank=True)),
                ('uebersiedlung_emigration', models.TextField(blank=True, verbose_name='Übersiedlung, Emigration, Remigration')),
                ('weitere_namensformen', models.TextField(blank=True)),
                ('geburtsdatum', models.TextField(blank=True)),
                ('sterbeort', models.TextField(blank=True)),
                ('geburtsort', models.TextField(blank=True)),
                ('religionen', models.TextField(blank=True)),
                ('name_text', models.TextField(blank=True, verbose_name='Name')),
                ('pseudonyme', models.TextField(blank=True)),
                ('oebl_werkverzeichnis', models.TextField(blank=True, verbose_name='ÖBL Werkverzeichnis')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('professioncategory', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apis_ontology.professioncategory')),
                ('self_contenttype', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model, apis_core.generic.abc.GenericModel),
        ),
        migrations.CreateModel(
            name='VersionPerson_title',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='apis_ontology.versionperson')),
                ('person', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apis_ontology.person')),
                ('title', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apis_ontology.title')),
            ],
            options={
                'verbose_name': 'VersionPerson_title',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VersionPerson_profession_mother',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='apis_ontology.versionperson')),
                ('parentprofession', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apis_ontology.parentprofession')),
                ('person', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apis_ontology.person')),
            ],
            options={
                'verbose_name': 'VersionPerson_profession_mother',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VersionPerson_profession_father',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='apis_ontology.versionperson')),
                ('parentprofession', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apis_ontology.parentprofession')),
                ('person', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apis_ontology.person')),
            ],
            options={
                'verbose_name': 'VersionPerson_profession_father',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VersionPerson_profession',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='apis_ontology.versionperson')),
                ('person', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apis_ontology.person')),
                ('profession', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apis_ontology.profession')),
            ],
            options={
                'verbose_name': 'VersionPerson_profession',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
