# Generated by Django 4.2.11 on 2024-04-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0031_versionperson_versionperson_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denomination',
            options={'verbose_name': 'Denomination', 'verbose_name_plural': 'Denominations'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ('name',), 'verbose_name': 'Profession', 'verbose_name_plural': 'Professions'},
        ),
        migrations.AlterModelOptions(
            name='professioncategory',
            options={'verbose_name': 'Profession Category', 'verbose_name_plural': 'Profession Categories'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Title', 'verbose_name_plural': 'Titles'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Work', 'verbose_name_plural': 'Works'},
        ),
    ]
