# Generated by Django 4.2.10 on 2024-04-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0032_alter_denomination_options_alter_event_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="adelspraedikat",
            field=models.TextField(blank=True, verbose_name="Adelsprädikat"),
        ),
        migrations.AlterField(
            model_name="person",
            name="religionen",
            field=models.TextField(blank=True, verbose_name="Religion(en)"),
        ),
        migrations.AlterField(
            model_name="person",
            name="soziale_herkunft",
            field=models.TextField(blank=True, verbose_name="Soziale Herkunft"),
        ),
        migrations.AlterField(
            model_name="person",
            name="weitere_namensformen",
            field=models.TextField(blank=True, verbose_name="Weiter Namensformen"),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="adelspraedikat",
            field=models.TextField(blank=True, verbose_name="Adelsprädikat"),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="religionen",
            field=models.TextField(blank=True, verbose_name="Religion(en)"),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="soziale_herkunft",
            field=models.TextField(blank=True, verbose_name="Soziale Herkunft"),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="weitere_namensformen",
            field=models.TextField(blank=True, verbose_name="Weiter Namensformen"),
        ),
    ]
