# Generated by Django 4.2.10 on 2024-04-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0033_alter_person_adelspraedikat_alter_person_religionen_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="berufe",
            field=models.TextField(blank=True, verbose_name="Beruf(e)"),
        ),
        migrations.AlterField(
            model_name="person",
            name="weitere_namensformen",
            field=models.TextField(blank=True, verbose_name="Weitere Namensformen"),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="berufe",
            field=models.TextField(blank=True, verbose_name="Beruf(e)"),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="weitere_namensformen",
            field=models.TextField(blank=True, verbose_name="Weitere Namensformen"),
        ),
    ]
