# Generated by Django 4.2.11 on 2024-06-25 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0038_person_alternative_names_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="professioncategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apis_ontology.professioncategory",
            ),
        ),
    ]
