# Generated by Django 5.1.2 on 2024-11-06 16:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import apis_core.generic.abc


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0040_dissertiertebeiunter_erhieltausbildungin_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("relations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArbeiteteZusammenMit",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("start_date", models.DateField(blank=True, editable=False, null=True)),
                (
                    "start_start_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "start_end_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                ("end_date", models.DateField(blank=True, editable=False, null=True)),
                (
                    "end_start_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "end_end_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "start_date_written",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Start"
                    ),
                ),
                (
                    "end_date_written",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="End"
                    ),
                ),
                (
                    "review",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Should be set to True, if the data record holds up quality standards.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, editable=False, max_length=100, null=True
                    ),
                ),
                ("references", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
        migrations.AlterField(
            model_name="dissertiertebeiunter",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="dissertiertebeiunter",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="erhieltausbildungin",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="erhieltausbildungin",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="graduiertean",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="graduiertean",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="habilitiertesichan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="habilitiertesichan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hatreligionszugehoerigkeit",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="hatreligionszugehoerigkeit",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hattealstrauzeugenzeugin",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="hattealstrauzeugenzeugin",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hatteleitungsfunktionan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="hatteleitungsfunktionan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hatteleitungsfunktionbei",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="hatteleitungsfunktionbei",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="institutioninstitutionlegacyrelation",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="institutioninstitutionlegacyrelation",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="kaempfteinbei",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="kaempfteinbei",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mitbiographiertunter",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="mitbiographiertunter",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="nahmteilan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="nahmteilan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personeventlegacyrelation",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="personeventlegacyrelation",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personinstitutionlegacyrelation",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="personinstitutionlegacyrelation",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personpersonlegacyrelation",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="personpersonlegacyrelation",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personplacelegacyrelation",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="personplacelegacyrelation",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personworklegacyrelation",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="personworklegacyrelation",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="placeplacelegacyrelation",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="placeplacelegacyrelation",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="promoviertean",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="promoviertean",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="standinkontaktmit",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="standinkontaktmit",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="starbin",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="starbin",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studiertelerntean",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="studiertelerntean",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versiondissertiertebeiunter",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versiondissertiertebeiunter",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionerhieltausbildungin",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionerhieltausbildungin",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versiongraduiertean",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versiongraduiertean",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionhabilitiertesichan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionhabilitiertesichan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionhatreligionszugehoerigkeit",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionhatreligionszugehoerigkeit",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionhattealstrauzeugenzeugin",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionhattealstrauzeugenzeugin",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionhatteleitungsfunktionan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionhatteleitungsfunktionan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionhatteleitungsfunktionbei",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionhatteleitungsfunktionbei",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versioninstitutioninstitutionlegacyrelation",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versioninstitutioninstitutionlegacyrelation",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionkaempfteinbei",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionkaempfteinbei",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionmitbiographiertunter",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionmitbiographiertunter",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionnahmteilan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionnahmteilan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionpersoneventlegacyrelation",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionpersoneventlegacyrelation",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionpersoninstitutionlegacyrelation",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionpersoninstitutionlegacyrelation",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionpersonpersonlegacyrelation",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionpersonpersonlegacyrelation",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionpersonplacelegacyrelation",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionpersonplacelegacyrelation",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionpersonworklegacyrelation",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionpersonworklegacyrelation",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionplaceplacelegacyrelation",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionplaceplacelegacyrelation",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionpromoviertean",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionpromoviertean",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionstandinkontaktmit",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionstandinkontaktmit",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionstarbin",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionstarbin",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionstudiertelerntean",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionstudiertelerntean",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwaraotitaoprofessorinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwaraotitaoprofessorinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarassistentinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarassistentinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwardekaninan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwardekaninan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarehrendoktorinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarehrendoktorinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarelternteilvon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarelternteilvon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwargeschwistervon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwargeschwistervon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwargrossvatermuttervon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwargrossvatermuttervon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarhonorardozentinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarhonorardozentinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarhonorarprofessorinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarhonorarprofessorinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarmitgliedvon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarmitgliedvon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarmitgruenderinvon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarmitgruenderinvon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarotitoprofessorinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarotitoprofessorinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarpatenkindvon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarpatenkindvon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarprivatdozentinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarprivatdozentinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarprofessorinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarprofessorinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarrektorinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarrektorinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarschuelerinvon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarschuelerinvon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarschwagerschwaegerinvon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarschwagerschwaegerinvon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarschwiegersohnschwiegertochtervon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarschwiegersohnschwiegertochtervon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwartaetigfuerwirkteanbei",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwartaetigfuerwirkteanbei",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarverheiratetmit",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarverheiratetmit",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwarverwandtmit",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwarverwandtmit",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwirkteforschtehieltsichaufin",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwirkteforschtehieltsichaufin",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwurdegeborenin",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="versionwurdegeborenin",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="waraotitaoprofessorinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="waraotitaoprofessorinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warassistentinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warassistentinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="wardekaninan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="wardekaninan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warehrendoktorinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warehrendoktorinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warelternteilvon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warelternteilvon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="wargeschwistervon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="wargeschwistervon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="wargrossvatermuttervon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="wargrossvatermuttervon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warhonorardozentinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warhonorardozentinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warhonorarprofessorinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warhonorarprofessorinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warmitgliedvon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warmitgliedvon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warmitgruenderinvon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warmitgruenderinvon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warotitoprofessorinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warotitoprofessorinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warpatenkindvon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warpatenkindvon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warprivatdozentinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warprivatdozentinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warprofessorinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warprofessorinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warrektorinan",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warrektorinan",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warschuelerinvon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warschuelerinvon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warschwagerschwaegerinvon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warschwagerschwaegerinvon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warschwiegersohnschwiegertochtervon",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warschwiegersohnschwiegertochtervon",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="wartaetigfuerwirkteanbei",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="wartaetigfuerwirkteanbei",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warverheiratetmit",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warverheiratetmit",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warverwandtmit",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="warverwandtmit",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="wirkteforschtehieltsichaufin",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="wirkteforschtehieltsichaufin",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="wurdegeborenin",
            name="review",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Should be set to True, if the data record holds up quality standards.",
            ),
        ),
        migrations.AlterField(
            model_name="wurdegeborenin",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.CreateModel(
            name="VersionArbeiteteZusammenMit",
            fields=[
                (
                    "relation_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="relations.relation",
                    ),
                ),
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("subj_object_id", models.PositiveIntegerField()),
                ("obj_object_id", models.PositiveIntegerField()),
                ("start_date", models.DateField(blank=True, editable=False, null=True)),
                (
                    "start_start_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "start_end_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                ("end_date", models.DateField(blank=True, editable=False, null=True)),
                (
                    "end_start_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "end_end_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "start_date_written",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Start"
                    ),
                ),
                (
                    "end_date_written",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="End"
                    ),
                ),
                (
                    "version_tag",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "review",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Should be set to True, if the data record holds up quality standards.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, editable=False, max_length=100, null=True
                    ),
                ),
                ("references", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "subj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical arbeitete zusammen mit",
                "verbose_name_plural": "historical arbeitete zusammen mits",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                models.Model,
                apis_core.generic.abc.GenericModel,
            ),
        ),
    ]
