# Generated by Django 5.1.4 on 2024-12-06 08:35

import django_json_editor_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0043_fandstattin_versionfandstattin"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="alternative_names_new",
            field=django_json_editor_field.fields.JSONEditorField(null=True),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="alternative_names_new",
            field=django_json_editor_field.fields.JSONEditorField(null=True),
        ),
    ]
