# Generated by Django 5.1.4 on 2024-12-06 08:35

import json

import django_json_editor_field.fields
from django.db import migrations


def convert_alternative_names(apps, schema_editor):
    """Convert alternative_names string field to JSON field alternative_names_new"""
    Person = apps.get_model("apis_ontology", "Person")

    for person in Person.objects.all():
        if person.alternative_names:
            # Split on newlines and filter out empty strings
            names = [
                {"art": "", "end": "", "name": name.strip(), "start": ""}
                for name in person.alternative_names.split("\n")
                if name.strip()
            ]
            # Convert to JSON format
            person.alternative_names_new = names
            person.save()


def reverse_convert(apps, schema_editor):
    """Reverse operation: convert JSON back to newline-separated string"""
    Person = apps.get_model("apis_ontology", "Person")

    for person in Person.objects.all():
        if person.alternative_names_new:
            names = json.loads(person.alternative_names_new)
            person.alternative_names = "\n".join(names)
            person.save()


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0043_fandstattin_versionfandstattin"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="alternative_names_new",
            field=django_json_editor_field.fields.JSONEditorField(null=True),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="alternative_names_new",
            field=django_json_editor_field.fields.JSONEditorField(null=True),
        ),
        migrations.RunPython(convert_alternative_names, reverse_code=reverse_convert),
        migrations.RemoveField(
            model_name="person",
            name="alternative_names",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="alternative_names",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="alternative_names_new",
            new_name="alternative_names",
        ),
        migrations.RenameField(
            model_name="versionperson",
            old_name="alternative_names_new",
            new_name="alternative_names",
        ),
    ]
