# Generated by Django 5.1.5 on 2025-02-20 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0044_person_alternative_names_new_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parentprofession",
            options={
                "verbose_name": "Parent Profession",
                "verbose_name_plural": "Parent Professions",
            },
        ),
    ]
