# Generated by Django 5.1.6 on 2025-02-26 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0045_alter_parentprofession_options"),
        ("apis_ontology", "0045_rename_end_start_date_event_end_date_from_and_more"),
    ]

    operations = []
