# Generated by Django 5.1.4 on 2024-12-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0045_auto_20241206_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='alternative_names',
        ),
        migrations.RemoveField(
            model_name='versionperson',
            name='alternative_names',
        ),
    ]
