# Generated by Django 5.1.4 on 2024-12-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0046_remove_person_alternative_names_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='alternative_names_new',
            new_name='alternative_names',
        ),
        migrations.RenameField(
            model_name='versionperson',
            old_name='alternative_names_new',
            new_name='alternative_names',
        ),
    ]
