# Generated by Django 5.1.7 on 2025-04-25 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0049_alter_place_feature_code_alter_place_label_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="institution",
            old_name="name",
            new_name="label",
        ),
        migrations.RenameField(
            model_name="versioninstitution",
            old_name="name",
            new_name="label",
        ),
    ]
