# Generated by Django 5.1.7 on 2025-04-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0050_rename_name_institution_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="label"
            ),
        ),
        migrations.AlterField(
            model_name="versioninstitution",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="label"
            ),
        ),
    ]
