# Generated by Django 5.1.7 on 2025-05-14 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0054_remove_versionarbeitetezusammenmit_version_tag_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arbeitetezusammenmit",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="dissertiertebeiunter",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="erhieltausbildungin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="fandstattin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="gelegenin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="graduiertean",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="habilitiertesichan",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="hatreligionszugehoerigkeit",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="hattealstrauzeugenzeugin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="hatteleitungsfunktionan",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="hatteleitungsfunktionbei",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="institutioninstitutionlegacyrelation",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="kaempfteinbei",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="mitbiographiertunter",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="nahmteilan",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="personeventlegacyrelation",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="personinstitutionlegacyrelation",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="personpersonlegacyrelation",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="personplacelegacyrelation",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="personworklegacyrelation",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="placeplacelegacyrelation",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="promoviertean",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="standinkontaktmit",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="starbin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="stiftete",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="stifteteinst",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="studiertelerntean",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="verliehenan",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="waraotitaoprofessorinan",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warassistentinan",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="wardekaninan",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warehrendoktorinan",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warelternteilvon",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="wargeburtstitelvon",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="wargeschwistervon",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="wargrossvatermuttervon",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warhonorardozentinan",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warhonorarprofessorinan",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warmitgliedvon",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warmitgruenderinvon",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warotitoprofessorinan",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warpatenkindvon",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warprivatdozentinan",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warprofessorinan",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warrektorinan",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warschuelerinvon",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warschwagerschwaegerinvon",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warschwiegersohnschwiegertochtervon",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="wartaetigfuerwirkteanbei",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warverheiratetmit",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="warverwandtmit",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="wirkteforschtehieltsichaufin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="wurdeerhobenin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="wurdegeborenin",
            options={"ordering": ["pk"]},
        ),
    ]
