# Generated by Django 5.1.7 on 2025-05-14 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0055_alter_arbeitetezusammenmit_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="denomination",
            options={
                "ordering": ["name"],
                "verbose_name": "Denomination",
                "verbose_name_plural": "Denominations",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["name"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AlterModelOptions(
            name="institution",
            options={
                "ordering": ["label"],
                "verbose_name": "Institution",
                "verbose_name_plural": "Institutions",
            },
        ),
        migrations.AlterModelOptions(
            name="nobility",
            options={
                "ordering": ["name"],
                "verbose_name": "Adelstitel",
                "verbose_name_plural": "Adelstitel",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["surname", "forename"],
                "verbose_name": "person",
                "verbose_name_plural": "persons",
            },
        ),
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["label"],
                "verbose_name": "place",
                "verbose_name_plural": "places",
            },
        ),
        migrations.AlterModelOptions(
            name="prize",
            options={
                "ordering": ["name"],
                "verbose_name": "Preis",
                "verbose_name_plural": "Preise",
            },
        ),
        migrations.AlterModelOptions(
            name="versionperson",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person",
                "verbose_name_plural": "historical persons",
            },
        ),
        migrations.AlterModelOptions(
            name="versionplace",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical place",
                "verbose_name_plural": "historical places",
            },
        ),
        migrations.AlterModelOptions(
            name="work",
            options={
                "ordering": ["name"],
                "verbose_name": "Work",
                "verbose_name_plural": "Works",
            },
        ),
    ]
