# Generated by Django 5.1.7 on 2025-05-14 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0056_alter_denomination_options_alter_event_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nobility",
            options={
                "ordering": ["name"],
                "verbose_name": "nobility",
                "verbose_name_plural": "nobilities",
            },
        ),
        migrations.AlterModelOptions(
            name="prize",
            options={
                "ordering": ["name"],
                "verbose_name": "prize",
                "verbose_name_plural": "prizes",
            },
        ),
        migrations.AlterModelOptions(
            name="versionprize",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical prize",
                "verbose_name_plural": "historical prizes",
            },
        ),
        migrations.AlterField(
            model_name="prize",
            name="part_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apis_ontology.prize",
                verbose_name="part of",
            ),
        ),
        migrations.AlterField(
            model_name="prize",
            name="tender_text",
            field=models.TextField(blank=True, null=True, verbose_name="tender text"),
        ),
        migrations.AlterField(
            model_name="versionprize",
            name="part_of",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.prize",
                verbose_name="part of",
            ),
        ),
        migrations.AlterField(
            model_name="versionprize",
            name="tender_text",
            field=models.TextField(blank=True, null=True, verbose_name="tender text"),
        ),
    ]
