# Generated by Django 5.1.7 on 2025-06-05 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0058_hatnominiert_versionhatnominiert"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="denomination",
            options={
                "ordering": ["label"],
                "verbose_name": "Denomination",
                "verbose_name_plural": "Denominations",
            },
        ),
        migrations.RenameField(
            model_name="denomination",
            old_name="name",
            new_name="label",
        ),
    ]
