# Generated by Django 5.1.7 on 2025-06-05 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0059_alter_denomination_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nobility",
            options={
                "ordering": ["label"],
                "verbose_name": "nobility",
                "verbose_name_plural": "nobilities",
            },
        ),
        migrations.RenameField(
            model_name="nobility",
            old_name="name",
            new_name="label",
        ),
    ]
