# Generated by Django 5.1.7 on 2025-06-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0060_alter_nobility_options_rename_name_nobility_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denomination",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="label"
            ),
        ),
    ]
