# Generated by Django 5.1.7 on 2025-06-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0061_alter_denomination_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nobility",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="label"
            ),
        ),
    ]
